sudo: required

services:
  - docker

before_install:
 - docker build -t app .

#  script:

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  
  - docker push app
